name: sporty
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1


environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  camera: ^0.9.4+19
  video_player: ^2.4.7
  path_provider: ^2.0.9
  permission_handler: ^10.2.0
  path: ^1.8.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2


dev_dependencies:
  go_router:
  flutter_riverpod:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  assets: 
    - assets/images/

  uses-material-design: true

